In [2]:
import numpy as np
import pandas as pd

In [14]:
dataset = pd.read_csv('50_Startups.csv')
#print(dataset)
X = dataset.iloc[ : , :-1].values
#print(X)
Y = dataset.iloc[ : , 4].values
#print(Y)

In [26]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder = LabelEncoder()
X[:, 3]= labelencoder.fit_transform(X[ : ,3])

onehotencoder = OneHotEncoder(categories='auto')
X = onehotencoder.fit_transform(X).toarray()
print(X)

[[1. 0. 0. ... 0. 0. 1.]
 [0. 1. 1. ... 1. 1. 0.]
 [1. 0. 0. ... 1. 1. 0.]
 ...
 [0. 1. 1. ... 1. 1. 0.]
 [1. 0. 0. ... 1. 1. 0.]
 [0. 1. 1. ... 1. 1. 0.]]


In [27]:
X = X[: , 1:]
print(X)

[[0. 0. 1. ... 0. 0. 1.]
 [1. 1. 0. ... 1. 1. 0.]
 [0. 0. 1. ... 1. 1. 0.]
 ...
 [1. 1. 0. ... 1. 1. 0.]
 [0. 0. 1. ... 1. 1. 0.]
 [1. 1. 0. ... 1. 1. 0.]]
